.TH "src/RobotController/Robot/MPU6050 Directory Reference" 3 "Tue Jul 22 2014" "Version 1.0" "Cubeception" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/RobotController/Robot/MPU6050 Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBI2Cdev\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBhelper_3dmath\&.h\fP"
.br
.ti -1c
.RI "file \fBMPU6050\&.cpp\fP"
.br
.ti -1c
.RI "file \fBMPU6050\&.h\fP"
.br
.ti -1c
.RI "file \fBMPU6050_6Axis_MotionApps20\&.h\fP"
.br
.ti -1c
.RI "file \fBMPU6050_9Axis_MotionApps41\&.h\fP"
.br
.in -1c
