.TH "Adafruit_PWMServoDriver" 3 "Tue Jul 22 2014" "Version 1.0" "Cubeception" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Adafruit_PWMServoDriver \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAdafruit_PWMServoDriver\fP (uint8_t addr=0x40)"
.br
.ti -1c
.RI "uint8_t \fBgetAddress\fP ()"
.br
.ti -1c
.RI "void \fBbegin\fP (void)"
.br
.ti -1c
.RI "void \fBreset\fP (void)"
.br
.ti -1c
.RI "void \fBsetPWMFreq\fP (float freq)"
.br
.ti -1c
.RI "void \fBsetPWM\fP (uint8_t num, uint16_t on, uint16_t off)"
.br
.ti -1c
.RI "void \fBsetMode1\fP (uint8_t d)"
.br
.ti -1c
.RI "void \fBsetMode2\fP (uint8_t d)"
.br
.ti -1c
.RI "uint8_t \fBgetMode1\fP ()"
.br
.ti -1c
.RI "uint8_t \fBgetMode2\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cubeception from the source code\&.
