.TH "Quaternion" 3 "Tue Jul 22 2014" "Version 1.0" "Cubeception" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Quaternion \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQuaternion\fP (float nw, float nx, float ny, float nz)"
.br
.ti -1c
.RI "\fBQuaternion\fP \fBgetProduct\fP (\fBQuaternion\fP q)"
.br
.ti -1c
.RI "\fBQuaternion\fP \fBgetConjugate\fP ()"
.br
.ti -1c
.RI "float \fBgetMagnitude\fP ()"
.br
.ti -1c
.RI "void \fBnormalize\fP ()"
.br
.ti -1c
.RI "\fBQuaternion\fP \fBgetNormalized\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBw\fP"
.br
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBz\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cubeception from the source code\&.
