.TH "TXPacket" 3 "Tue Jul 22 2014" "Version 1.0" "Cubeception" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TXPacket \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TXPacket\&.h>\fP
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBPacketController\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Handles output to serial port 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cubeception from the source code\&.
