.TH "VectorInt16" 3 "Tue Jul 22 2014" "Version 1.0" "Cubeception" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VectorInt16 \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVectorInt16\fP (int16_t nx, int16_t ny, int16_t nz)"
.br
.ti -1c
.RI "float \fBgetMagnitude\fP ()"
.br
.ti -1c
.RI "void \fBnormalize\fP ()"
.br
.ti -1c
.RI "\fBVectorInt16\fP \fBgetNormalized\fP ()"
.br
.ti -1c
.RI "void \fBrotate\fP (\fBQuaternion\fP *q)"
.br
.ti -1c
.RI "\fBVectorInt16\fP \fBgetRotated\fP (\fBQuaternion\fP *q)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int16_t \fBx\fP"
.br
.ti -1c
.RI "int16_t \fBy\fP"
.br
.ti -1c
.RI "int16_t \fBz\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cubeception from the source code\&.
